# Generated by Django 5.0.3 on 2024-03-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tareas', models.CharField(max_length=100)),
                ('completadas', models.BooleanField(default=False)),
                ('creadas', models.DateField(auto_now_add=True)),
                ('actualizadas', models.DateField(auto_now=True)),
            ],
        ),
    ]
